### ISSUE TITLE
Can we have a LICENSE for the package?

### ISSUE THREAD

**Issue by fangohr** [pearu/pyvtk#13]
I'd like to make PyVTK available through conda-forge, and it would be helpful (maybe required) to have a LICENSE for pyvtk.

I can offer a pull request, maybe with a BSD 3 license, or any other license the author (@pearu) would prefer.

Many thanks,

Hans

**Comment by pearu** [comment]
PyVTK has BSD license as specified in README file.
Feel free to upload a LICENSE file in a form that conda-forge requires.
Thanks, Pearu

**Comment by fangohr** [comment]
Thanks, and sorry - I should have closed this when you merged the pull request.
